// Key definitions of the SONY RM-DM9 remote

#ifndef __SONY_RM_DM9_H__
#define __SONY_RM_DM9_H__

#define SONY_RM_DM9_KEYS\
  SIRCS_DATA( KEY_PLAY_PAUSE, 107 ),\
  SIRCS_DATA( KEY_STOP, 56 ),\
  SIRCS_DATA( KEY_PREV, 48 ),\
  SIRCS_DATA( KEY_NEXT, 49 ),\
  SIRCS_DATA( KEY_REPEAT, 44 ),\
  SIRCS_DATA( KEY_1, 0 ),\
  SIRCS_DATA( KEY_2, 1 ),\
  SIRCS_DATA( KEY_3, 2 ),\
  SIRCS_DATA( KEY_VOLUME_UP, 18 ),\
  SIRCS_DATA( KEY_4, 3 ),\
  SIRCS_DATA( KEY_5, 4 ),\
  SIRCS_DATA( KEY_6, 5 ),\
  SIRCS_DATA( KEY_VOLUME_DOWN, 19 ),\
  SIRCS_DATA( KEY_7, 6 ),\
  SIRCS_DATA( KEY_8, 7 ),\
  SIRCS_DATA( KEY_9, 8 ),\
  SIRCS_DATA( KEY_10, 9 ),\
  SIRCS_DATA( KEY_10_PLUS, 39 )
  
#define SIRCS_RESET_KEY       KEY_REPEAT  

#endif
 